Chat message delete new
Zaista/secretsanta pull request #29
Opened 2023-09-21 10:29 UTC by nemanja777

We implemented delete chat message. I hope now it's work.

2023-09-21 11:32 UTC, Zaista requested changes

2023-09-21 11:32 UTC, Zaista commented on public/css/santaChat.css
> + /* margin-top: 20px;*/
remove comments

2023-09-21 11:50 UTC, nemanja777 commented on public/css/santaChat.css
> + /* margin-top: 20px;*/
comments has been removed

2023-09-27 15:46 UTC, Zaista approved these changes

2023-09-27 15:46 UTC, merged